name: Build images for registry

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    name: Building and pushing docker images to the GitHub Registry
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      -
        name: Build and Push - latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/made/alpine-node:latest
      -
        name: Build and Push - release
        if: ${{ github.event.release.tag_name }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/made/alpine-node:${{ github.event.release.tag_name }}
      -
        name: Build and Push - dev image
        if: ${{ github.event.release.tag_name }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/made/alpine-node:${{ github.event.release.tag_name }}-dev

